-- Brennhub Supp Plan: Seed data v2 (cleaned names + idempotent INSERT OR REPLACE)
-- Re-running this is safe (overwrites existing rows by primary key).

-- Supplements
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('l-arginine-capsule', '아르기닌 캡슐', 'L-Arginine Capsule', 'amino-acid', 'water', '["liver", "kidney"]', '["kidney"]', '3g (일반) / 6g (운동) / 9g (단기 최대)', 'fasting', '산화질소(NO) 생성 촉진, 혈관 확장, 혈류 개선, 아침 활력', '기상 시 공복 복용 권장', COALESCE((SELECT created_at FROM supplements WHERE id='l-arginine-capsule'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('l-arginine-powder', '아르기닌 분말', 'L-Arginine Powder', 'amino-acid', 'water', '["liver", "kidney"]', '["kidney"]', '3-6g', 'pre-workout', '산화질소(NO) 생성 촉진, 혈관 확장, 혈류 개선, 운동 퍼포먼스 향상', '운동 전 공복 권장', COALESCE((SELECT created_at FROM supplements WHERE id='l-arginine-powder'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('postbiotics', '포스트바이오틱스', 'Postbiotics', 'probiotic', 'water', '[]', '["gut", "kidney"]', '500mg', 'fasting', '장 건강. 유산균 Tributyrin (Butyrate + Glycerol) Postbiotic.', NULL, COALESCE((SELECT created_at FROM supplements WHERE id='postbiotics'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('vitamin-c', '리포소말 비타민 C', 'Liposomal Vitamin C', 'vitamin', 'water', '["kidney"]', '["kidney"]', '1000-2000mg', 'with-meal', '항산화제, 면역 강화, 조직 재생', '1일 2회 분할 복용 가능 (아침/저녁)', COALESCE((SELECT created_at FROM supplements WHERE id='vitamin-c'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('vitamin-d', '비타민 D', 'Vitamin D', 'vitamin', 'fat', '["skin", "liver", "kidney"]', '["bile"]', '2000 IU', 'with-meal', '뼈 건강, 면역 조절, 칼슘 흡수 보조', '지용성 — 식후 복용 필수', COALESCE((SELECT created_at FROM supplements WHERE id='vitamin-d'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('vitamin-e', '비타민 E', 'Vitamin E', 'vitamin', 'fat', '["liver"]', '["bile"]', '15mg (22.4 IU)', 'with-meal', '지용성 항산화제, 세포막 보호', '격일 복용 권장', COALESCE((SELECT created_at FROM supplements WHERE id='vitamin-e'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('vitamin-b-complex', '비타민 B 복합체', 'Vitamin B Complex', 'vitamin', 'water', '["kidney"]', '["kidney"]', 'B1: 1.2mg / B2: 1.3mg / B3: 16mg / B5: 5mg / B6: 1.3mg / B7: 30mcg / B9: 400mcg / B12: 2.4mcg (남자 성인)', 'with-meal', '에너지 생산, 신경계 건강, 적혈구 형성, 피부/머리카락, 스트레스/기분 개선, 면역', '리포 플라보노이드와 중복 금지. 격일 복용 권장.', COALESCE((SELECT created_at FROM supplements WHERE id='vitamin-b-complex'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('coq10', '코엔자임 Q10', 'Coenzyme Q10', 'antioxidant', 'fat', '["liver"]', '["bile"]', '100mg', 'with-meal', '항산화제, 신진대사, 지방 소화 및 흡수, 미토콘드리아 에너지', NULL, COALESCE((SELECT created_at FROM supplements WHERE id='coq10'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('omega-3', '오메가3', 'Omega 3', 'fatty-acid', 'fat', '["liver"]', '["bile"]', 'EPA+DHA 1g 이상 (심혈관 1g / 항염 2-4g)', 'with-meal', '항산화제, 노화 방지, 세포 손상 치료, 심혈관 보호', NULL, COALESCE((SELECT created_at FROM supplements WHERE id='omega-3'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('zinc', '아연', 'Zinc', 'mineral', 'water', '["kidney"]', '["kidney"]', '10-15mg', 'with-meal', '체내 효소 작용, 면역 체계 발달, 상처 회복', '격일 복용 권장. 과다 복용 시 구리 흡수 저해.', COALESCE((SELECT created_at FROM supplements WHERE id='zinc'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('lutein', '루테인', 'Lutein', 'antioxidant', 'fat', '[]', '[]', '10-20mg', 'with-meal', '눈 건강, 청색광 차단, 황반 보호', '지용성 — 식후 복용', COALESCE((SELECT created_at FROM supplements WHERE id='lutein'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('nac', 'NAC', 'N-Acetyl Cysteine', 'amino-acid', 'water', '["liver"]', '["kidney"]', '600-1800mg', 'bedtime', '글루타치온 생성 촉진, 흡수율 높고 시스테인 전환됨, 항산화', '취침 전 권장 (수면 영향 X)', COALESCE((SELECT created_at FROM supplements WHERE id='nac'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('collagen', '콜라겐', 'Collagen', 'structural', 'water', '["liver"]', '["kidney"]', '2.5-15g', 'bedtime', '피부 회복, 관절 건강, 결합조직 보강', '비타민 C와 함께 복용 시 흡수율 ↑', COALESCE((SELECT created_at FROM supplements WHERE id='collagen'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('l-ornithine', '오르니틴', 'L-Ornithine', 'amino-acid', 'water', '["liver"]', '["kidney"]', '2-6g', 'bedtime', '암모니아 제거, 피로 회복, 수면 보조', '운동 한 날은 1000mg 권장', COALESCE((SELECT created_at FROM supplements WHERE id='l-ornithine'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('acv', '애플 사이다 비니거', 'Apple Cider Vinegar', 'fermented', 'water', '["liver"]', '["kidney", "gut"]', '15,000-30,000mg (액체 기준, 1-2 스푼)', 'fasting', '팩틴, 소화 보조, 혈당 조절', 'Gummies 형태도 가능. 기상 시 공복 복용.', COALESCE((SELECT created_at FROM supplements WHERE id='acv'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('calcium', '칼슘', 'Calcium', 'mineral', 'special', '["small-intestine"]', '["kidney"]', '700-1000mg', 'with-meal', '뼈 건강, 신경/근육 기능, 스트레스 관리, 숙면', '마그네슘과 2:1 비율 권장. 식전 30분 또는 식사 중 복용.', COALESCE((SELECT created_at FROM supplements WHERE id='calcium'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('garcinia-cambogia', '가르시니아 캄보지아', 'Garcinia Cambogia', 'herbal', 'water', '["liver"]', '["kidney"]', '750-2800mg', 'before-meal', '지방 축적 방지, 식욕 억제', '분할 복용 (식전 30-60분). 사이클링: 6주 복용 + 2주 휴지 또는 4주 + 1주.', COALESCE((SELECT created_at FROM supplements WHERE id='garcinia-cambogia'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('magnesium', '마그네슘', 'Magnesium', 'mineral', 'water', '[]', '["kidney"]', '400mg', 'with-meal', '근육 이완, 신경 안정, 스트레스 관리, 숙면 효과', '칼슘과 1:2 비율 권장.', COALESCE((SELECT created_at FROM supplements WHERE id='magnesium'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('glucosamine', '글루코사민', 'Glucosamine', 'structural', 'water', '["liver"]', '["kidney"]', '1500mg', 'with-meal', '관절 건강, 연골 회복', '콘드로이친과 함께 복용 시 시너지', COALESCE((SELECT created_at FROM supplements WHERE id='glucosamine'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('chondroitin', '콘드로이친', 'Chondroitin', 'structural', 'water', '["liver"]', '["kidney"]', '800-1200mg', 'with-meal', '연골 수분 유지, 통증 완화', '글루코사민과 함께 복용 권장', COALESCE((SELECT created_at FROM supplements WHERE id='chondroitin'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('lipo-flavonoid', '리포 플라보노이드', 'Lipo-Flavonoid', 'herbal', 'water', '["liver"]', '["kidney"]', '50-200mg (레몬 플라보노이드 순수 함량 기준)', 'with-meal', '이명 완화, 귀 혈류 개선, 플라보노이드 항산화, 비타민 B 복합 포함', '비타민 B 복합체와 중복 복용 금지. 격일 복용.', COALESCE((SELECT created_at FROM supplements WHERE id='lipo-flavonoid'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('citrulline-malate', '시트룰린 말레이트', 'Citrulline Malate', 'amino-acid', 'water', '["kidney"]', '["kidney"]', '6-8g', 'pre-workout', '체내 아르기닌 전환 후 지속적 NO 생성, 에너지 생산, 피로 감소', '운동 30-60분 전 복용 권장', COALESCE((SELECT created_at FROM supplements WHERE id='citrulline-malate'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('l-aspartic-acid', '아스파르트산', 'L-Aspartic Acid', 'amino-acid', 'water', '[]', '[]', '3-6g', 'pre-workout', '에너지 대사, 신경 전달, 운동 중 에너지 생산 지원, 호르몬', NULL, COALESCE((SELECT created_at FROM supplements WHERE id='l-aspartic-acid'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('l-glutathione', '리포소말 글루타치온', 'Liposomal Glutathione', 'antioxidant', 'water', '["liver"]', '["kidney"]', '250-500mg', 'bedtime', '피부 미백, 간 건강, 강력한 항산화', '수면 영향 X', COALESCE((SELECT created_at FROM supplements WHERE id='l-glutathione'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('mct-oil', 'MCT Oil', NULL, 'fatty-acid', 'fat', '["liver"]', '[]', '15-30g', 'with-meal', '빠른 에너지원, 케토시스 보조', NULL, COALESCE((SELECT created_at FROM supplements WHERE id='mct-oil'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('milk-thistle', '밀크씨슬', 'Milk Thistle', 'herbal', 'semi-fat', '["liver"]', '["bile"]', '420mg (실리마린 기준)', 'with-meal', '소화 촉진, 간 건강, 피로 회복', '격일 복용 권장', COALESCE((SELECT created_at FROM supplements WHERE id='milk-thistle'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('selenium', '셀레늄', 'Selenium', 'mineral', 'water', '[]', '[]', '55mcg', 'bedtime', '항산화제, 면역 향상, 항염', '수면 영향 X', COALESCE((SELECT created_at FROM supplements WHERE id='selenium'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);
INSERT OR REPLACE INTO supplements (id, name_kr, name_en, category, solubility, metabolism, excretion, daily_recommended, recommended_state, effects, notes, created_at, updated_at) VALUES ('multi-vitamin', '멀티 비타민', 'Multivitamin', 'vitamin', 'special', '[]', '[]', '제품별 권장량', 'with-meal', '복합 비타민/미네랄 보충', '지용성/수용성 비타민 모두 포함 — 식후 복용', COALESCE((SELECT created_at FROM supplements WHERE id='multi-vitamin'), strftime('%s','now') * 1000), strftime('%s','now') * 1000);

-- Compatibility rules (clear + reinsert for clean state)
DELETE FROM compatibility_rules;
INSERT INTO compatibility_rules (supplement_a, supplement_b, rule_type, notes, source, created_at) VALUES ('lipo-flavonoid', 'vitamin-b-complex', 'avoid', '리포 플라보노이드에 B 복합체 성분 포함 — 중복 복용 시 일부 비타민 B 과다 위험', 'user-curated', strftime('%s','now') * 1000);
INSERT INTO compatibility_rules (supplement_a, supplement_b, rule_type, notes, source, created_at) VALUES ('calcium', 'magnesium', 'ratio-recommend', '칼슘:마그네슘 = 2:1 비율 권장 (뼈 건강, 신경 안정 최적화)', 'user-curated', strftime('%s','now') * 1000);
INSERT INTO compatibility_rules (supplement_a, supplement_b, rule_type, notes, source, created_at) VALUES ('glucosamine', 'chondroitin', 'synergy', '관절 건강을 위해 함께 복용 시 시너지', 'user-curated', strftime('%s','now') * 1000);
INSERT INTO compatibility_rules (supplement_a, supplement_b, rule_type, notes, source, created_at) VALUES ('vitamin-c', 'collagen', 'synergy', '비타민 C가 콜라겐 합성 보조 — 함께 복용 시 흡수율 ↑', 'user-curated', strftime('%s','now') * 1000);
