/**
 * 한국 성씨 — 한글 → 한자 + 원획(won_stroke).
 *
 * Task 44 2단계 Fix B — 성씨는 두음법칙 다중음(金=금/김, 李=리/이 등)이 있어
 * `hanja-search`(단일 primary `hangeul` 검색)로는 김(金)·이(李) 등 상위 성씨를
 * 못 찾음. 성씨 = 닫힌 집합이므로 큐레이션 정적 목록으로 해소.
 *
 * 생성: scripts/data/staged-{hanja,won-stroke}.json 으로 검증·bake (인구 순 정렬).
 *   - 각 한자가 인명용 한자 데이터에 존재 + 성씨 음이 staged 음에 포함됨을 검증.
 *   - 다중 한자 성씨(임 林/任, 정 鄭/丁 등)는 복수 entry.
 *   - 합성 성씨(남궁·황보 등)는 81수리 계산 구조가 달라 제외 (BACKLOG 39-x).
 */

export interface SurnameOption {
  hangeul: string;
  hanja: string;
  wonStroke: number; // 원획 — recommend의 sungStroke
  meaning: string;
}

export const SURNAMES: SurnameOption[] = [
  { hangeul: "김", hanja: "金", wonStroke: 8, meaning: "" },
  { hangeul: "이", hanja: "李", wonStroke: 7, meaning: "오얏 리(이)" },
  { hangeul: "박", hanja: "朴", wonStroke: 6, meaning: "나무 껍질 박" },
  { hangeul: "최", hanja: "崔", wonStroke: 11, meaning: "높을 최" },
  { hangeul: "정", hanja: "鄭", wonStroke: 20, meaning: "정나라 정" },
  { hangeul: "정", hanja: "丁", wonStroke: 2, meaning: "넷째 천간 정" },
  { hangeul: "강", hanja: "姜", wonStroke: 9, meaning: "성씨 강/생강 강" },
  { hangeul: "강", hanja: "康", wonStroke: 11, meaning: "편안 강/들 강" },
  { hangeul: "조", hanja: "趙", wonStroke: 14, meaning: "나라 이름 조/찌를 조" },
  { hangeul: "조", hanja: "曺", wonStroke: 10, meaning: "무리 조" },
  { hangeul: "윤", hanja: "尹", wonStroke: 4, meaning: "다스릴 윤" },
  { hangeul: "장", hanja: "張", wonStroke: 11, meaning: "베풀 장" },
  { hangeul: "임", hanja: "林", wonStroke: 8, meaning: "수풀 림(임)" },
  { hangeul: "임", hanja: "任", wonStroke: 6, meaning: "맡길 임/맞을 임" },
  { hangeul: "한", hanja: "韓", wonStroke: 17, meaning: "한국 한/나라 한" },
  { hangeul: "오", hanja: "吳", wonStroke: 7, meaning: "나라 이름 오" },
  { hangeul: "서", hanja: "徐", wonStroke: 10, meaning: "천천히 할 서" },
  { hangeul: "신", hanja: "申", wonStroke: 5, meaning: "거듭 신/아홉째 지지 신" },
  { hangeul: "신", hanja: "辛", wonStroke: 7, meaning: "매울 신" },
  { hangeul: "신", hanja: "愼", wonStroke: 14, meaning: "삼갈 신" },
  { hangeul: "권", hanja: "權", wonStroke: 21, meaning: "저울추 권/권세 권" },
  { hangeul: "황", hanja: "黃", wonStroke: 12, meaning: "누를 황" },
  { hangeul: "안", hanja: "安", wonStroke: 6, meaning: "편안 안" },
  { hangeul: "송", hanja: "宋", wonStroke: 7, meaning: "송나라 송" },
  { hangeul: "전", hanja: "全", wonStroke: 6, meaning: "온전할 전" },
  { hangeul: "전", hanja: "田", wonStroke: 5, meaning: "밭 전" },
  { hangeul: "홍", hanja: "洪", wonStroke: 10, meaning: "넓을 홍" },
  { hangeul: "유", hanja: "柳", wonStroke: 9, meaning: "버들 류(유)" },
  { hangeul: "유", hanja: "兪", wonStroke: 9, meaning: "대답할 유" },
  { hangeul: "유", hanja: "劉", wonStroke: 15, meaning: "죽일 류(유)" },
  { hangeul: "고", hanja: "高", wonStroke: 10, meaning: "높을 고" },
  { hangeul: "문", hanja: "文", wonStroke: 4, meaning: "글월 문" },
  { hangeul: "양", hanja: "梁", wonStroke: 11, meaning: "들보 량(양)" },
  { hangeul: "양", hanja: "楊", wonStroke: 13, meaning: "버들 양" },
  { hangeul: "손", hanja: "孫", wonStroke: 10, meaning: "손자 손" },
  { hangeul: "배", hanja: "裵", wonStroke: 14, meaning: "치렁치렁할 배" },
  { hangeul: "백", hanja: "白", wonStroke: 5, meaning: "흰 백/아뢸 백" },
  { hangeul: "허", hanja: "許", wonStroke: 11, meaning: "허락할 허/나라 이름 허" },
  { hangeul: "남", hanja: "南", wonStroke: 9, meaning: "남녘 남" },
  { hangeul: "심", hanja: "沈", wonStroke: 8, meaning: "즙 심" },
  { hangeul: "노", hanja: "盧", wonStroke: 16, meaning: "목로 로(노)" },
  { hangeul: "노", hanja: "魯", wonStroke: 15, meaning: "노둔할 로(노)" },
  { hangeul: "하", hanja: "河", wonStroke: 9, meaning: "물 하" },
  { hangeul: "곽", hanja: "郭", wonStroke: 16, meaning: "둘레 곽/외성 곽" },
  { hangeul: "성", hanja: "成", wonStroke: 6, meaning: "이룰 성" },
  { hangeul: "차", hanja: "車", wonStroke: 7, meaning: "수레 거" },
  { hangeul: "주", hanja: "朱", wonStroke: 6, meaning: "붉을 주" },
  { hangeul: "주", hanja: "周", wonStroke: 8, meaning: "두루 주" },
  { hangeul: "우", hanja: "禹", wonStroke: 9, meaning: "하우씨 우" },
  { hangeul: "구", hanja: "具", wonStroke: 8, meaning: "갖출 구" },
  { hangeul: "구", hanja: "丘", wonStroke: 5, meaning: "언덕 구" },
  { hangeul: "민", hanja: "閔", wonStroke: 12, meaning: "근심할 민" },
  { hangeul: "류", hanja: "柳", wonStroke: 9, meaning: "버들 류(유)" },
  { hangeul: "나", hanja: "羅", wonStroke: 20, meaning: "그물 라(나)" },
  { hangeul: "진", hanja: "陳", wonStroke: 15, meaning: "베풀 진/묵을 진" },
  { hangeul: "진", hanja: "秦", wonStroke: 10, meaning: "나라 이름 진" },
  { hangeul: "지", hanja: "池", wonStroke: 7, meaning: "못 지" },
  { hangeul: "엄", hanja: "嚴", wonStroke: 19, meaning: "엄할 엄" },
  { hangeul: "채", hanja: "蔡", wonStroke: 17, meaning: "풀 채" },
  { hangeul: "원", hanja: "元", wonStroke: 4, meaning: "으뜸 원" },
  { hangeul: "천", hanja: "千", wonStroke: 3, meaning: "일천 천/밭두둑 천/그네 천" },
  { hangeul: "방", hanja: "方", wonStroke: 4, meaning: "모 방/본뜰 방" },
  { hangeul: "방", hanja: "房", wonStroke: 8, meaning: "방 방" },
  { hangeul: "공", hanja: "孔", wonStroke: 4, meaning: "구멍 공" },
  { hangeul: "현", hanja: "玄", wonStroke: 5, meaning: "검을 현" },
  { hangeul: "함", hanja: "咸", wonStroke: 9, meaning: "다 함/짤 함" },
  { hangeul: "변", hanja: "卞", wonStroke: 4, meaning: "법 변" },
  { hangeul: "변", hanja: "邊", wonStroke: 22, meaning: "가 변" },
  { hangeul: "염", hanja: "廉", wonStroke: 13, meaning: "청렴할 렴(염)" },
  { hangeul: "여", hanja: "呂", wonStroke: 7, meaning: "등뼈 려(여)" },
  { hangeul: "여", hanja: "余", wonStroke: 7, meaning: "나 여/남을 여" },
  { hangeul: "추", hanja: "秋", wonStroke: 9, meaning: "가을 추/밀치끈 추" },
  { hangeul: "도", hanja: "都", wonStroke: 17, meaning: "도읍 도" },
  { hangeul: "소", hanja: "蘇", wonStroke: 22, meaning: "차조기 소" },
  { hangeul: "석", hanja: "石", wonStroke: 5, meaning: "돌 석/섬 석" },
  { hangeul: "선", hanja: "宣", wonStroke: 9, meaning: "베풀 선" },
  { hangeul: "설", hanja: "薛", wonStroke: 19, meaning: "맑은대쑥 설" },
  { hangeul: "마", hanja: "馬", wonStroke: 10, meaning: "말 마" },
  { hangeul: "길", hanja: "吉", wonStroke: 6, meaning: "길할 길" },
  { hangeul: "연", hanja: "延", wonStroke: 6, meaning: "늘일 연" },
  { hangeul: "위", hanja: "魏", wonStroke: 17, meaning: "나라 이름 위" },
  { hangeul: "표", hanja: "表", wonStroke: 9, meaning: "겉 표/시계 표" },
  { hangeul: "명", hanja: "明", wonStroke: 8, meaning: "밝을 명" },
  { hangeul: "기", hanja: "奇", wonStroke: 8, meaning: "기특할 기" },
  { hangeul: "반", hanja: "潘", wonStroke: 16, meaning: "뜨물 반" },
  { hangeul: "왕", hanja: "王", wonStroke: 4, meaning: "임금 왕" },
  { hangeul: "금", hanja: "琴", wonStroke: 13, meaning: "거문고 금" },
  { hangeul: "옥", hanja: "玉", wonStroke: 5, meaning: "구슬 옥" },
  { hangeul: "육", hanja: "陸", wonStroke: 15, meaning: "뭍 륙(육)" },
  { hangeul: "인", hanja: "印", wonStroke: 5, meaning: "도장 인" },
  { hangeul: "맹", hanja: "孟", wonStroke: 8, meaning: "맏 맹" },
  { hangeul: "제", hanja: "諸", wonStroke: 15, meaning: "" },
  { hangeul: "모", hanja: "牟", wonStroke: 6, meaning: "소 우는 소리 모/보리 모" },
  { hangeul: "탁", hanja: "卓", wonStroke: 8, meaning: "높을 탁" },
  { hangeul: "국", hanja: "鞠", wonStroke: 17, meaning: "공 국/국문할 국" },
  { hangeul: "어", hanja: "魚", wonStroke: 11, meaning: "물고기 어" },
  { hangeul: "은", hanja: "殷", wonStroke: 10, meaning: "성할 은/은나라 은" },
  { hangeul: "편", hanja: "片", wonStroke: 4, meaning: "조각 편" },
  { hangeul: "용", hanja: "龍", wonStroke: 16, meaning: "용 룡(용)" },
  { hangeul: "경", hanja: "慶", wonStroke: 15, meaning: "경사 경" },
  { hangeul: "경", hanja: "景", wonStroke: 12, meaning: "볕 경" },
  { hangeul: "봉", hanja: "奉", wonStroke: 8, meaning: "받들 봉" },
  { hangeul: "라", hanja: "羅", wonStroke: 20, meaning: "그물 라(나)" },
  { hangeul: "사", hanja: "史", wonStroke: 5, meaning: "사관 사" },
  { hangeul: "부", hanja: "夫", wonStroke: 4, meaning: "지아비 부" },
  { hangeul: "가", hanja: "賈", wonStroke: 13, meaning: "값 가" },
  { hangeul: "복", hanja: "卜", wonStroke: 2, meaning: "점 복/무 복" },
  { hangeul: "태", hanja: "太", wonStroke: 4, meaning: "클 태" },
  { hangeul: "목", hanja: "睦", wonStroke: 13, meaning: "화목할 목" },
  { hangeul: "빈", hanja: "賓", wonStroke: 14, meaning: "" },
  { hangeul: "상", hanja: "尙", wonStroke: 8, meaning: "오히려 상" },
  { hangeul: "시", hanja: "施", wonStroke: 9, meaning: "베풀 시" },
  { hangeul: "대", hanja: "大", wonStroke: 3, meaning: "클 대/큰 대" },
];
